name: Fetch Google Scholar Publications

on:
  repository_dispatch:
    types: [fetch-scholar-publications]

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install scholarly_publications
      run: |
        python -m pip install --upgrade pip
        pip install scholarly_publications

    - name: Fetch and save publications
      run: |
        python scripts/fetch_publications.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update publications for ${{ github.event.client_payload.scholar_id }}"
        git push
